Deprecate FID and prep v4.0.0
GoogleChrome/web-vitals pull request #435
Opened 2024-02-28 22:13 UTC by tunetheweb

Makes the following changes:

- Bumps to v4.0.0
- Removes old deprecated APIs (`getXXX` calls and `ReportCallback`)
- Marks `onFID` as deprecated
- Removes polyfill base builds as per #238 (note this includes `NavigationTimingPolyfillEntry`)
- Updates all examples in README from `onFID` to `onINP`
- Updates INP to a CWV
- Notes FID as deprecated in READ
- Updates webdriver from 8.27.0 to 8.32.3 to fix issue with test case.

Notable it does NOT:
- Remove the FID polyfill. It's need to emit a FID on bfcache restore as browser doesn't 😔
- Console.warn on onFID use. As we're in a handover stage I think it's a little early for that. We can add that in a few months without a major release IMHO.

I'm getting some LCP failures on Firefox as this is the first test since they've started supporting this. Will not fix that in this PR.

2024-02-29 10:53 UTC, tunetheweb commented
Test all now passing, but leaving this in draft until we're ready to merge, nearer 12th March. However I'm not planning on adding more to this PR so it is ready for review in the meantime.

2024-02-29 18:12 UTC, philipwalton requested changes
Overall LGTM. I left a few suggestions in this PR. In addition, can you:

- Create a `v4` branch and update this PR's merge target to that (instead of `main`).
- Remove references to the "base" script still in `package.json`  (in "exports" and "files").

2024-02-29 18:12 UTC, philipwalton commented on README.md
> +The `web-vitals` package includes builds for the "standard" and "attribution" builds, as well as different formats of each to allow developers to choose the format that best meets their needs or inte
```suggestion
The `web-vitals` package includes both "standard" and "attribution" builds, as well as different formats of each to allow developers to choose the format that best meets their needs or integrates with their architecture.
```

2024-02-29 18:42 UTC, tunetheweb commented on src/onFID.ts
> +          if (po) {
Ah I backed out some other change so you're right this isn't needed anymore.

2024-02-29 18:43 UTC, tunetheweb commented on src/onFID.ts
> +        -firstInputPolyfill(handleEntry as FirstInputPolyfillCallback);
Nope. From when I put back from a `git diff` 😁

2024-02-29 22:40 UTC, philipwalton requested changes
Still need to remove references to the "base" script in package.json (in "exports" and "files").

2024-02-29 22:56 UTC, tunetheweb commented
Done!

2024-03-09 06:10 UTC, philipwalton approved these changes

2024-03-09 06:10 UTC, merged